CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    elo INT DEFAULT 1200,
    matches_played INT DEFAULT 0,
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS match_history (
    id SERIAL PRIMARY KEY,
    winner_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    loser_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    winner_elo_change INT NOT NULL DEFAULT 0,
    loser_elo_change INT NOT NULL DEFAULT 0,
    mode VARCHAR(20) DEFAULT 'online',
    ended_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
